
services:

 # first mongo db so that backend can connect to backend
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .  # Path to backend Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env file
    depends_on:
      - mongo

  frontend:
    build: ./my-app  # Path to frontend Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./my-app/.env  # Load environment variables from frontend .env file
    depends_on:
      - backend

  

volumes:
  mongo-data: